require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BednetsAndIllinessesController do

  # This should return the minimal set of attributes required to create a valid
  # BednetsAndIlliness. As you add validations to BednetsAndIlliness, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "county" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BednetsAndIllinessesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bednets_and_illinesses as @bednets_and_illinesses" do
      bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bednets_and_illinesses).should eq([bednets_and_illiness])
    end
  end

  describe "GET show" do
    it "assigns the requested bednets_and_illiness as @bednets_and_illiness" do
      bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
      get :show, {:id => bednets_and_illiness.to_param}, valid_session
      assigns(:bednets_and_illiness).should eq(bednets_and_illiness)
    end
  end

  describe "GET new" do
    it "assigns a new bednets_and_illiness as @bednets_and_illiness" do
      get :new, {}, valid_session
      assigns(:bednets_and_illiness).should be_a_new(BednetsAndIlliness)
    end
  end

  describe "GET edit" do
    it "assigns the requested bednets_and_illiness as @bednets_and_illiness" do
      bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
      get :edit, {:id => bednets_and_illiness.to_param}, valid_session
      assigns(:bednets_and_illiness).should eq(bednets_and_illiness)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BednetsAndIlliness" do
        expect {
          post :create, {:bednets_and_illiness => valid_attributes}, valid_session
        }.to change(BednetsAndIlliness, :count).by(1)
      end

      it "assigns a newly created bednets_and_illiness as @bednets_and_illiness" do
        post :create, {:bednets_and_illiness => valid_attributes}, valid_session
        assigns(:bednets_and_illiness).should be_a(BednetsAndIlliness)
        assigns(:bednets_and_illiness).should be_persisted
      end

      it "redirects to the created bednets_and_illiness" do
        post :create, {:bednets_and_illiness => valid_attributes}, valid_session
        response.should redirect_to(BednetsAndIlliness.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bednets_and_illiness as @bednets_and_illiness" do
        # Trigger the behavior that occurs when invalid params are submitted
        BednetsAndIlliness.any_instance.stub(:save).and_return(false)
        post :create, {:bednets_and_illiness => { "county" => "invalid value" }}, valid_session
        assigns(:bednets_and_illiness).should be_a_new(BednetsAndIlliness)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BednetsAndIlliness.any_instance.stub(:save).and_return(false)
        post :create, {:bednets_and_illiness => { "county" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bednets_and_illiness" do
        bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
        # Assuming there are no other bednets_and_illinesses in the database, this
        # specifies that the BednetsAndIlliness created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BednetsAndIlliness.any_instance.should_receive(:update_attributes).with({ "county" => "MyString" })
        put :update, {:id => bednets_and_illiness.to_param, :bednets_and_illiness => { "county" => "MyString" }}, valid_session
      end

      it "assigns the requested bednets_and_illiness as @bednets_and_illiness" do
        bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
        put :update, {:id => bednets_and_illiness.to_param, :bednets_and_illiness => valid_attributes}, valid_session
        assigns(:bednets_and_illiness).should eq(bednets_and_illiness)
      end

      it "redirects to the bednets_and_illiness" do
        bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
        put :update, {:id => bednets_and_illiness.to_param, :bednets_and_illiness => valid_attributes}, valid_session
        response.should redirect_to(bednets_and_illiness)
      end
    end

    describe "with invalid params" do
      it "assigns the bednets_and_illiness as @bednets_and_illiness" do
        bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BednetsAndIlliness.any_instance.stub(:save).and_return(false)
        put :update, {:id => bednets_and_illiness.to_param, :bednets_and_illiness => { "county" => "invalid value" }}, valid_session
        assigns(:bednets_and_illiness).should eq(bednets_and_illiness)
      end

      it "re-renders the 'edit' template" do
        bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BednetsAndIlliness.any_instance.stub(:save).and_return(false)
        put :update, {:id => bednets_and_illiness.to_param, :bednets_and_illiness => { "county" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bednets_and_illiness" do
      bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
      expect {
        delete :destroy, {:id => bednets_and_illiness.to_param}, valid_session
      }.to change(BednetsAndIlliness, :count).by(-1)
    end

    it "redirects to the bednets_and_illinesses list" do
      bednets_and_illiness = BednetsAndIlliness.create! valid_attributes
      delete :destroy, {:id => bednets_and_illiness.to_param}, valid_session
      response.should redirect_to(bednets_and_illinesses_url)
    end
  end

end
