require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataMiningsController do

  # This should return the minimal set of attributes required to create a valid
  # DataMining. As you add validations to DataMining, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataMiningsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all data_minings as @data_minings" do
      data_mining = DataMining.create! valid_attributes
      get :index, {}, valid_session
      assigns(:data_minings).should eq([data_mining])
    end
  end

  describe "GET show" do
    it "assigns the requested data_mining as @data_mining" do
      data_mining = DataMining.create! valid_attributes
      get :show, {:id => data_mining.to_param}, valid_session
      assigns(:data_mining).should eq(data_mining)
    end
  end

  describe "GET new" do
    it "assigns a new data_mining as @data_mining" do
      get :new, {}, valid_session
      assigns(:data_mining).should be_a_new(DataMining)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_mining as @data_mining" do
      data_mining = DataMining.create! valid_attributes
      get :edit, {:id => data_mining.to_param}, valid_session
      assigns(:data_mining).should eq(data_mining)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataMining" do
        expect {
          post :create, {:data_mining => valid_attributes}, valid_session
        }.to change(DataMining, :count).by(1)
      end

      it "assigns a newly created data_mining as @data_mining" do
        post :create, {:data_mining => valid_attributes}, valid_session
        assigns(:data_mining).should be_a(DataMining)
        assigns(:data_mining).should be_persisted
      end

      it "redirects to the created data_mining" do
        post :create, {:data_mining => valid_attributes}, valid_session
        response.should redirect_to(DataMining.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_mining as @data_mining" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataMining.any_instance.stub(:save).and_return(false)
        post :create, {:data_mining => {  }}, valid_session
        assigns(:data_mining).should be_a_new(DataMining)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataMining.any_instance.stub(:save).and_return(false)
        post :create, {:data_mining => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_mining" do
        data_mining = DataMining.create! valid_attributes
        # Assuming there are no other data_minings in the database, this
        # specifies that the DataMining created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataMining.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => data_mining.to_param, :data_mining => { "these" => "params" }}, valid_session
      end

      it "assigns the requested data_mining as @data_mining" do
        data_mining = DataMining.create! valid_attributes
        put :update, {:id => data_mining.to_param, :data_mining => valid_attributes}, valid_session
        assigns(:data_mining).should eq(data_mining)
      end

      it "redirects to the data_mining" do
        data_mining = DataMining.create! valid_attributes
        put :update, {:id => data_mining.to_param, :data_mining => valid_attributes}, valid_session
        response.should redirect_to(data_mining)
      end
    end

    describe "with invalid params" do
      it "assigns the data_mining as @data_mining" do
        data_mining = DataMining.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataMining.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_mining.to_param, :data_mining => {  }}, valid_session
        assigns(:data_mining).should eq(data_mining)
      end

      it "re-renders the 'edit' template" do
        data_mining = DataMining.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataMining.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_mining.to_param, :data_mining => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_mining" do
      data_mining = DataMining.create! valid_attributes
      expect {
        delete :destroy, {:id => data_mining.to_param}, valid_session
      }.to change(DataMining, :count).by(-1)
    end

    it "redirects to the data_minings list" do
      data_mining = DataMining.create! valid_attributes
      delete :destroy, {:id => data_mining.to_param}, valid_session
      response.should redirect_to(data_minings_url)
    end
  end

end
