require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrescriptionLinesController do

  # This should return the minimal set of attributes required to create a valid
  # PrescriptionLine. As you add validations to PrescriptionLine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "quantity" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrescriptionLinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prescription_lines as @prescription_lines" do
      prescription_line = PrescriptionLine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prescription_lines).should eq([prescription_line])
    end
  end

  describe "GET show" do
    it "assigns the requested prescription_line as @prescription_line" do
      prescription_line = PrescriptionLine.create! valid_attributes
      get :show, {:id => prescription_line.to_param}, valid_session
      assigns(:prescription_line).should eq(prescription_line)
    end
  end

  describe "GET new" do
    it "assigns a new prescription_line as @prescription_line" do
      get :new, {}, valid_session
      assigns(:prescription_line).should be_a_new(PrescriptionLine)
    end
  end

  describe "GET edit" do
    it "assigns the requested prescription_line as @prescription_line" do
      prescription_line = PrescriptionLine.create! valid_attributes
      get :edit, {:id => prescription_line.to_param}, valid_session
      assigns(:prescription_line).should eq(prescription_line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrescriptionLine" do
        expect {
          post :create, {:prescription_line => valid_attributes}, valid_session
        }.to change(PrescriptionLine, :count).by(1)
      end

      it "assigns a newly created prescription_line as @prescription_line" do
        post :create, {:prescription_line => valid_attributes}, valid_session
        assigns(:prescription_line).should be_a(PrescriptionLine)
        assigns(:prescription_line).should be_persisted
      end

      it "redirects to the created prescription_line" do
        post :create, {:prescription_line => valid_attributes}, valid_session
        response.should redirect_to(PrescriptionLine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prescription_line as @prescription_line" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrescriptionLine.any_instance.stub(:save).and_return(false)
        post :create, {:prescription_line => { "quantity" => "invalid value" }}, valid_session
        assigns(:prescription_line).should be_a_new(PrescriptionLine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrescriptionLine.any_instance.stub(:save).and_return(false)
        post :create, {:prescription_line => { "quantity" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prescription_line" do
        prescription_line = PrescriptionLine.create! valid_attributes
        # Assuming there are no other prescription_lines in the database, this
        # specifies that the PrescriptionLine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PrescriptionLine.any_instance.should_receive(:update_attributes).with({ "quantity" => "MyString" })
        put :update, {:id => prescription_line.to_param, :prescription_line => { "quantity" => "MyString" }}, valid_session
      end

      it "assigns the requested prescription_line as @prescription_line" do
        prescription_line = PrescriptionLine.create! valid_attributes
        put :update, {:id => prescription_line.to_param, :prescription_line => valid_attributes}, valid_session
        assigns(:prescription_line).should eq(prescription_line)
      end

      it "redirects to the prescription_line" do
        prescription_line = PrescriptionLine.create! valid_attributes
        put :update, {:id => prescription_line.to_param, :prescription_line => valid_attributes}, valid_session
        response.should redirect_to(prescription_line)
      end
    end

    describe "with invalid params" do
      it "assigns the prescription_line as @prescription_line" do
        prescription_line = PrescriptionLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrescriptionLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => prescription_line.to_param, :prescription_line => { "quantity" => "invalid value" }}, valid_session
        assigns(:prescription_line).should eq(prescription_line)
      end

      it "re-renders the 'edit' template" do
        prescription_line = PrescriptionLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrescriptionLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => prescription_line.to_param, :prescription_line => { "quantity" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prescription_line" do
      prescription_line = PrescriptionLine.create! valid_attributes
      expect {
        delete :destroy, {:id => prescription_line.to_param}, valid_session
      }.to change(PrescriptionLine, :count).by(-1)
    end

    it "redirects to the prescription_lines list" do
      prescription_line = PrescriptionLine.create! valid_attributes
      delete :destroy, {:id => prescription_line.to_param}, valid_session
      response.should redirect_to(prescription_lines_url)
    end
  end

end
